---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
imagePullSecrets:
- name: regcred

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hokusai-integration-test
  namespace: default
imagePullSecrets:
- name: regcred
