---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ project_name }}-web
  namespace: default
  labels:
    app: {{ project_name }}
    component: web
    layer: application
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ project_name }}
      component: web
      layer: application
  template:
    metadata:
      labels:
        app: {{ project_name }}
        component: web
        layer: application
      name: {{ project_name }}-web
    spec:
      containers:
      - name: {{ project_name }}-web
        envFrom:
        - configMapRef:
            name: {{ project_name }}-environment
        image: {{ project_repo }}:staging
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ project_name }}
    component: web
    layer: application
  name: {{ project_name }}-web
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ project_name }}
    component: web
    layer: application
  type: ClusterIP
